### ISSUE TITLE
Prepare for sharing with BurtCo

### ISSUE THREAD

**Issue by kmcelwee** [dpinney/coopforecast#93]
- [ ] Upload BurtCo data and perform trial run
- [x] Writeup explanation of remaining features / current limitations
- [x] Point to instructions
